source 'http://rubygems.org'

gem 'rails', '3.0.6'
gem 'haml', '>=3.0.18'
gem 'rspec-rails'

gem 'bettertabs'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
gem 'ruby-debug19', :require => 'ruby-debug'