source 'http://rubygems.org'


gem 'rails', '3.0.9'
gem 'rake', '0.9.2'
gem 'rspec-rails'
gem 'haml', '3.1.2'

gem 'bettertabs', '1.2.2'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
gem 'ruby-debug19', :require => 'ruby-debug'